name: nightly

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '18 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - run: |
          pwd
          git clone https://github.com/periskop-dev/periskop
          git clone https://github.com/periskop-dev/periskop-pushgateway

          pushd periskop

          # build server
          git rev-parse HEAD
          CGO_ENABLED=0 go build -o periskop .
          strip periskop

          # build web
          pushd web
          npm install
          npm run build

          # popd
          popd
          popd
          pushd periskop-pushgateway

          # build pushgateway
          git rev-parse HEAD
          CGO_ENABLED=0 go build .
          strip periskop-pushgateway

      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            periskop-pushgateway/periskop-pushgateway
            periskop/periskop
            periskop/web/dist

